title: ovestrum.github.io
description: A ovestrum site
theme: just-the-docs

url: https://ovestrum.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
