title: ovestrum.github.io
description: ovestrum.github.com
theme: just-the-docs

url: https://ovestrum.github.io
color_scheme: dark

logo: "/_assets/images/favicon.svg"

aux_links:
  Repositories: https://github.com/ovestrum
  LinkedIn: https://www.linkedin.com/in/ovestrum/
  Google Scholar: https://scholar.google.no/citations?user=6VJbdkoAAAAJ