title: ovestrum.github.io
description: ovestrum.github.com
theme: just-the-docs

url: https://ovestrum.github.io
color_scheme: dark

logo: "/_assets/images/cv.png"
favicon_ico: "/_assets/images/favicon.svg"

aux_links:
  Repositories: https://github.com/ovestrum
