title: ovestrum
description: A ovestrum page
theme: just-the-docs

url: https://ovestrum.github.io
color_scheme: dark

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
