title: ovestrum.github.io
description: ovestrum.github.com
theme: just-the-docs

url: https://ovestrum.github.io
color_scheme: dark

logo: "/assets/images/cv.png"
#favicon: "/_assets/images/favicon-32x32.png"

aux_links:
  Github: https://github.com/ovestrum
  LinkedIn: https://www.linkedin.com/in/ovestrum/
  Google Scholar: https://scholar.google.no/citations?user=6VJbdkoAAAAJ
 
footer_content: "Copyright &copy; 2023 Ole Vestrum. Distributed by an <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red